//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Visual Studio via: 
//     Edit > Paste Special > Paste JSON as Classes
//     
//     JSON generated from: /DefaultCollection/_apis/wit/workitems?ids=3,4&fields=System.Id,System.Title,System.Description,System.State,System.CreatedDate,System.CreatedBy,System.WorkItemType&api-version=1.0
//
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace Inedo.Extensions.TFS.VisualStudioOnline.Model
{
    public class GetWorkItemsResponse
    {
        public int count { get; set; }
        public GetWorkItemResponse[] value { get; set; }
    }

    public class GetWorkItemResponse
    {
        public int id { get; set; }
        public int rev { get; set; }
        public Dictionary<string, object> fields { get; set; }
        public string url { get; set; }
        public _Links _links { get; set; }
    }
}
