//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Visual Studio via: 
//     Edit > Paste Special > Paste JSON as Classes
//     
//     JSON generated from: /DefaultCollection/TestProject1/_apis/work/teamsettings/iterations?api-version=2.0
//
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inedo.Extensions.TFS.VisualStudioOnline.Model
{
    public class GetIterationsResponse
    {
        public int count { get; set; }
        public GetIterationResponse[] value { get; set; }
    }

    public class GetIterationResponse
    {
        public string id { get; set; }
        public string name { get; set; }
        public string path { get; set; }
        public Attributes attributes { get; set; }
        public string url { get; set; }
    }

    public class Attributes
    {
        public object startDate { get; set; }
        public object finishDate { get; set; }
    }

}
